---
  driver:
    name: vagrant

  provisioner:
    name: ansible_playbook
    hosts: all
    require_ansible_repo: true
    require_chef_for_busser: false
    require_ruby_for_busser: false
    ansible_verbose: true
    ansible_verbosity: 3
    playbook: /tasks/playbook.yml
    roles_path: ../cloud_ansible/

  platforms:
    - name: ubuntu-16.04

  verifier:
    name: inspec

  suites:
    - name: cloud_computing
      # run_list:
        # - recipe[cloud_ansible::default]
      # verifier:
        # inspec_tests:
          # - test/integration/default
      # attributes: