- name: Add configurations for Ubuntu
  hosts: all
  become: yes
  remote_user: root
  # become_user: sudo
  # become_method: su
  roles:
    - common
  vars:
    group_name: 'Group 1'
    group_members: ['Burrows','Karner','Vrtis']
    lecturer: 'Kappel/Christoph'
    change_me: 'change me'
    
  tasks:
    - name: Create Template for MOTD
      template:
        src: create_motd.j2
        dest: /etc/motd
        mode: '0440'
        owner: root
        force: yes
  
    # - name: Create Lecturer Group
      # group:
        # name: lecturer
        # state: present
        
    # - name: Add Kappel User
      # user:
        # name: ckappel
        # home: /home/kappelc
        # shell: /bin/zsh
        # generate_ssh_key: yes
        # state: present
        
    # - name: Add Nimmervoll User
      # user:
        # name: animmervoll
        # home: /home/nimm
        # shell: /bin/bash
        # group: lecturer
        # state: present
        
    # - name: Configure sudo permission
      # lineinfile:
        # dest: /etc/sudoers.d/ckappel
        # line: 'ckappel ALL=(ALL) NOPASSWD: ALL'
        # create: yes
        # state: present
        
    # # - name: Set authorized key taken from file
      # # authorized_key:
        # # user: ckappel
        # # state: present
        # # key: "{{ lookup('file', '/home/ckappel/.ssh/id_rsa.pub') }}"
    
    # - name: install openssh-server
      # package: 
        # name: openssh-server
        # state: latest
        
    # - name: Disallow root ssh logins
      # # lineinfile:
        # # dest: /etc/ssh/sshd_config
        # # regexp: '^#PermitRootLogin'
        # # line: 'PermitRootLogin no'
        # # create: yes
        # # state: present
        
      # lineinfile:
        # dest: /etc/ssh/sshd_config
        # regexp: 'PermitRootLogin'
        # line: 'PermitRootLogin no'
        # create: yes
        # state: present
        
    # - name: Disable protocol version 1 and enable version 2
      # lineinfile:
        # dest: /etc/ssh/sshd_config
        # regexp: 'Protocol'
        # line: 'Protocol 2'
        # create: yes
        # state: present
        
    # - name: Allow users ssh access
      # lineinfile:
        # dest: /etc/ssh/sshd_config
        # regexp: 'AllowUsers'
        # line: 'AllowUsers ckappel animmervoll'
        # create: yes
        # state: present
        

        
